---
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 19090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - 13000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana:/var/lib/grafana

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    ports:
      - 18123:8123
      - 19000:9000


volumes:
  grafana:
