---
services:
  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - 13000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboard.json:/etc/grafana/dashboards/dashboard.json
      - grafana:/var/lib/grafana

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    volumes:
      - ./clickhouse:/docker-entrypoint-initdb.d
    ports:
      - 18123:8123
      - 19000:9000


volumes:
  grafana:
