{
 "title": "New dashboard",
 "time": { "from": "2024-08-09T20:57:58.777Z", "to": "2024-12-22T06:39:13.435Z" },
 "panels": [
  { "title": "total distance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "distance per month",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "rawSql": "SELECT \n    toStartOfMonth(time) AS month,  -- Группируем по началу месяца\n    (max(totaldistance) - min(totaldistance)) / 1000 AS monthly_km  -- Разница в километрах за месяц\nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\n    AND totaldistance != 0\nGROUP BY \n    month\nHAVING \n    monthly_km >= 1\nORDER BY \n    month\n"
    }
   ]
  },
  {
   "title": "total distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \n    toStartOfMinute(time) AS time_interval,  -- округляем время до минут (можно настроить на более мелкие интервалы)\n    totaldistance / 1000 as total_km\nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\n    and totaldistance != 0\nORDER BY \n    time_interval\n"
    }
   ]
  },
  {
   "title": "total distance km by selected period",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (max(totaldistance) - min(totaldistance)) / 1000\nFROM metrics\nWHERE $__timeFilter(time)\nAND totaldistance != 0"
    }
   ]
  },
  {
   "title": "distance per day",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "distance per day (time series)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "lengthkm" } },
     "targets": [
      {
       "rawSql": "SELECT \n    toDate(time) AS date,  -- Группируем по дате (без времени)\n    (max(totaldistance) - min(totaldistance)) / 1000 AS daily_km  -- Разница в километрах за день\nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\n    AND totaldistance != 0\nGROUP BY \n    date\nORDER BY \n    date\n"
      }
     ]
    },
    {
     "title": "distance per day (bar chart)",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 19, "x": 5, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT \n    toDate(time) AS date,  -- Группируем по дате (без времени)\n    (max(totaldistance) - min(totaldistance)) / 1000 AS daily_km  -- Разница в километрах за день\nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\n    AND totaldistance != 0\nGROUP BY \n    date\nHAVING \n    daily_km >= 1\nORDER BY \n    date\n"
      }
     ]
    }
   ]
  },
  {
   "title": "max speed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "max, avg speed km/h",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
     "targets": [
      {
       "rawSql": "SELECT \n    toDate(time) AS date,\n    max(speed),\n    avg(speed)\nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\n    AND speed > 2\nGROUP BY \n    date\nORDER BY \n    date\n"
      }
     ]
    },
    {
     "title": "max speed km/h",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 19, "x": 5, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT \n    toDate(time) AS date,  -- Группируем по дате (без времени)\n    max(speed) \nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\nGROUP BY \n    date\nHAVING\n  max(speed) > 0\nORDER BY \n    date\n"
      }
     ]
    }
   ]
  },
  { "title": "max pwm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "max, avg pwm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    toDate(time) AS date,\n    max(pwm),\n    max(speed)\nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\n    AND speed > 2\nGROUP BY \n    date\nORDER BY \n    date\n"
    }
   ]
  },
  {
   "title": "max pwm %",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \n    toDate(time) AS date, \n    max(pwm) \nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\n    AND speed > 2\nGROUP BY \n    date\nORDER BY \n    date\n"
    }
   ]
  },
  { "title": "avg speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "avg speed, avg pwm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT \n    toDate(time) AS date,\n    avg(pwm),\n    avg(speed)\nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\n    AND speed > 2\nGROUP BY \n    date\nORDER BY \n    date\n"
    }
   ]
  },
  {
   "title": "avg speed km/h",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT \n    toDate(time) AS date, \n    avg(speed) \nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\n    AND speed > 2\nGROUP BY \n    date\nHAVING\n  max(speed) > 0\nORDER BY \n    date\n"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "avg power, max power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT \n    toDate(time) AS date,\n    max(power),\n    avg(power)\nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\n    AND speed > 2\nGROUP BY \n    date\nORDER BY \n    date\n"
    }
   ]
  },
  {
   "title": "avg power watt",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT \n    toDate(time) AS date, \n    avg(power) \nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\n    AND speed > 2\nGROUP BY \n    date\nHAVING\n  max(speed) > 0\nORDER BY \n    date\n"
    }
   ]
  },
  { "title": "avg pwm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "max, avg pwm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    toDate(time) AS date,\n    max(pwm),\n    avg(pwm)\nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\n    AND speed > 2\nGROUP BY \n    date\nORDER BY \n    date\n"
    }
   ]
  },
  {
   "title": "avg pwm %",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT \n    toDate(time) AS date, \n    avg(pwm) \nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\n    AND speed > 2\nGROUP BY \n    date\nORDER BY \n    date\n"
    }
   ]
  },
  { "title": "avg battery level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "avg battery level ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    toDate(time) AS date,\n    avg(battery_level)\nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\n    AND speed > 2\nGROUP BY \n    date\nORDER BY \n    date\n"
    },
    {
     "rawSql": "SELECT \n    toDate(time) AS date,\n    avg(battery_level)\nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\n    AND speed <= 2\nGROUP BY \n    date\nORDER BY \n    date\n"
    }
   ]
  },
  {
   "title": "avg battery level % idle",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT \n    toDate(time) AS date, \n    avg(battery_level) \nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\n    AND speed = 0\nGROUP BY \n    date\nORDER BY \n    date\n"
    }
   ]
  },
  {
   "title": "max temp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "avg, max temp",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "SELECT \n    toDate(time) AS date,\n    avg(temp2),\n    avg(system_temp),\n    max(temp2),\n    max(system_temp)\nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\nGROUP BY \n    date\nORDER BY \n    date\n"
      }
     ]
    },
    {
     "title": "max temp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 106 },
     "targets": [
      {
       "rawSql": "SELECT \n    toDate(time) AS date, \n    max(system_temp)\nFROM \n    metrics\nWHERE \n    $__timeFilter(time)\n    AND totaldistance != 0\nGROUP BY \n    date\nORDER BY \n    date\n"
      }
     ]
    }
   ]
  }
 ]
}